### PR TITLE
Adding DockerMonitor project

### PR DESCRIPTION
**Pull request by pburma**
Simple Vantiq Client Builder application that can monitor docker containers resource utilization for the local host system. 

The utilization data is provided by the docker API.

Instructions on how to enable the Docker API and make it accessible to the containers is available here: 
https://github.com/pburma/vantiqexamples/tree/master/docker_examples/system_monitor

Once the docker API is active and accessible this project will load usage data from each container. 
image

This information can be used to create custom alerts and monitor system health. For example to send a low disk space alert or high CPU utilization notification.

### CODE REVIEW

**Comment by rblumer4** [comment]
would be good to add the description/link in the PR description to the Project description for the DockerMonitor project.
Just pulling the git repo doesn't mean you will see this PR description...

**Comment by pburma** [comment]
I can add a readme.md file with the details.

**Comment by pburma** [comment]
Committed a readme file with description, will make a point to include one in future submissions

**Comment by rblumer4** [comment]
one more question:  when I run the client, I get this error:
> Exception: One or more custom assets failed to load: 
 ../../docs/Docker.js

I didn't see anything in the directions about downloading it from anywhere.
Is there a missing Docker.js document in the export?

**Comment by pburma** [comment]
That's a shame, its both part of the client and JS generated as part of the service. It should be included in the project export automatically I think but clearly it wasn't. 

I added it manually, should work now.

**Review by rblumer4 — APPROVED** [review]
LGTM

**Comment by rblumer4** [comment]
> That's a shame, its both part of the client and JS generated as part of the service. It should be included in the project export automatically I think but clearly it wasn't.

Adding the service-doc when creating or adding a service to a project was fixed in v1.33, but if your project/service was created before that, maybe the project didn't get updated or saved.  
Saving the client also adds its docs to the project (checked that in v1.33).  But you have to save the project after that or it will get lost.
I did notice that just ADDING an existing client to a project doesn't add its documents to the project.  
Filed that as Vantiq/vantiq-issues#410

**Pull request merged**
