### PR TITLE
Updated Assembly Tutorial to use packaged resources

### LINKED ISSUE #16: Update assembly tutorial project to be packaged
Update all the resources in the assembly tutorial to be inside the `.com.vantiq.weatherEmergencies` package

### PR DESCRIPTION
**Pull request by dnhuch**
Since we want to encourage assembly authors to make all of the assembly resources packaged, it seemed prudent to update the tutorial to have all of the resources in a package.

Close #16

### CODE REVIEW

**Review by rblumer4 — COMMENTED** [review]
seems to import OK, but haven't looked at this in any detail.
couple of questions:
* do we use _com.vantiq_ or _io.vantiq_ for our package names?
* can the top-level directory be called WeatherEmergency without the full package name?
If not, then I think we at least want the ZIP file to have the shorter name, for the Import -> Contributions pick-list....
* do we really want the full package name in the Project name?   It makes the Projects list very wide...
image

**Comment by sfitts** [comment]
> * do we use _com.vantiq_ or _io.vantiq_ for our package names?

`io.vantiq` is reserved for use by our system code (in the fullness of time).  For demos/tutorials we have been using `com.vantiq`.

**Comment by dnhuch** [comment]
I think we want to give the project the fully packaged name for the same reason we want the resources packaged. Having everything named in the assembly live in a package significantly reduces the likelihood of collision in any consuming namespace. This applies to the project name equally.

But we can make the top level directory just WeatherEmergencyProject.

**Review by rblumer4 — DISMISSED** [review]
LGTM
One nit:  the graphs for the 2 apps are REALLY small again after this import.
Can you adjust their scale again?
The 2 collaborationTypes are small, too, though with fewer bubbles the task names are still readable.  Ideally you could scale them up, too.

**Comment by dnhuch** [comment]
Just updated the project to rescale all the graphs so it should look better now!

**Review by rblumer4 — APPROVED** [review]
that's better. Thanks!

**Pull request merged**
